//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PawnshopUnchuMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServices
    {
        public string servID { get; set; }
        public string servName { get; set; }
    }
}
